/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class staff extends javax.swing.JFrame {

    /**
     * Creates new form staff
     */
    public staff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        save = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        back = new javax.swing.JButton();
        salary = new javax.swing.JLabel();
        joindate = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        post = new javax.swing.JLabel();
        workhour = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        leavedate = new javax.swing.JLabel();
        salarytxt = new javax.swing.JTextField();
        jointxt = new javax.swing.JTextField();
        leavetxt = new javax.swing.JTextField();
        posttxt = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        hour = new javax.swing.JTextField();
        mantxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        save.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 528, -1, -1));

        reset.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 528, -1, -1));

        back.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        salary.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        salary.setText("Salary");
        getContentPane().add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 131, 114, -1));

        joindate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        joindate.setText("Joining date");
        getContentPane().add(joindate, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 183, 114, 36));

        name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        name.setText("Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 69, 114, -1));

        post.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        post.setForeground(new java.awt.Color(255, 255, 255));
        post.setText("Work post");
        getContentPane().add(post, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 317, 114, 36));

        workhour.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        workhour.setForeground(new java.awt.Color(255, 255, 255));
        workhour.setText("Daily work hour");
        getContentPane().add(workhour, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 379, 114, 32));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Manager ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 448, 114, 32));

        leavedate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        leavedate.setText("Leave date");
        getContentPane().add(leavedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 249, 114, 36));
        getContentPane().add(salarytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 121, 185, 37));
        getContentPane().add(jointxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 183, 185, 36));
        getContentPane().add(leavetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 249, 185, 36));
        getContentPane().add(posttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 317, 185, 36));

        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });
        getContentPane().add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 60, 185, 35));
        getContentPane().add(hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 379, 185, 32));

        mantxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantxtActionPerformed(evt);
            }
        });
        getContentPane().add(mantxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 448, 185, 32));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/s.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 590));

        setSize(new java.awt.Dimension(916, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.toBack();
        setVisible(false);
        new home().toFront();
        new home().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_backActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        nametxt.setText("");
        salarytxt.setText("");
        jointxt.setText("");
        leavetxt.setText("");
        posttxt.setText("");
        hour.setText("");
        mantxt.setText("");

    }//GEN-LAST:event_resetActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void mantxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mantxtActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String StaffName = nametxt.getText();
        String Staff_salary =  salarytxt.getText();
        String Staff_join_date = jointxt.getText();
        String Staff_leave_date = leavetxt.getText();
        String Staff_work_as = posttxt.getText();
        String Staff_work_hour = hour.getText();
        String ManagerID = mantxt.getText();
        
        try {
            Connection con = ConnectMSSQL.getCon();
            Statement st = con.createStatement();
            String query = "insert into Staff(StaffName,Staff_salary, Staff_join_date,Staff_leave_date,Staff_work_as, Staff_work_hour, ManagerID)values(?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);

            pst.setString(1, nametxt.getText());
            pst.setString(2, salarytxt.getText());
            pst.setString(3,jointxt.getText());
            pst.setString(4, leavetxt.getText());
            pst.setString(5, posttxt.getText());
            pst.setString(6,  hour.getText());
            pst.setString(7, mantxt.getText());
            
            
             pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted successfully!");

        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "UnSucessFully Updated");
             System.out.println("notconnect");
        }
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField hour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel joindate;
    private javax.swing.JTextField jointxt;
    private javax.swing.JLabel leavedate;
    private javax.swing.JTextField leavetxt;
    private javax.swing.JTextField mantxt;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel post;
    private javax.swing.JTextField posttxt;
    private javax.swing.JButton reset;
    private javax.swing.JLabel salary;
    private javax.swing.JTextField salarytxt;
    private javax.swing.JButton save;
    private javax.swing.JLabel workhour;
    // End of variables declaration//GEN-END:variables
}
