/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class trainer extends javax.swing.JFrame {

    /**
     * Creates new form trainer
     */
    public trainer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nametxt = new javax.swing.JTextField();
        workhour = new javax.swing.JLabel();
        salarytxt = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jointxt = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        back = new javax.swing.JButton();
        worktxt = new javax.swing.JTextField();
        salary = new javax.swing.JLabel();
        joindate = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        rating = new javax.swing.JLabel();
        ratingtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 60, 185, 35));

        workhour.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        workhour.setForeground(new java.awt.Color(240, 240, 240));
        workhour.setText("Daily work hour");
        getContentPane().add(workhour, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 100, 114, 40));
        getContentPane().add(salarytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 229, 185, 37));

        save.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 492, 79, -1));
        getContentPane().add(jointxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 296, 185, 34));

        reset.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 492, 75, -1));

        back.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));
        getContentPane().add(worktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 100, 185, 40));

        salary.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        salary.setForeground(new java.awt.Color(240, 240, 240));
        salary.setText("Salary");
        getContentPane().add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 230, 114, 34));

        joindate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        joindate.setForeground(new java.awt.Color(240, 240, 240));
        joindate.setText("Joining date");
        getContentPane().add(joindate, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 296, 114, 35));

        name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(240, 240, 240));
        name.setText("Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 69, 114, -1));

        rating.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rating.setForeground(new java.awt.Color(240, 240, 240));
        rating.setText("Rating for work");
        getContentPane().add(rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 169, 100, 34));
        getContentPane().add(ratingtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 169, 185, 34));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/t.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 590));

        setSize(new java.awt.Dimension(916, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.toBack();
        setVisible(false);
        new home().toFront();
        new home().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_backActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        nametxt.setText("");
        salarytxt.setText("");
        jointxt.setText("");
        worktxt.setText("");
        ratingtxt.setText("");
        

    }//GEN-LAST:event_resetActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String Trainer_name = nametxt.getText();
        String Trainer_work_hour = worktxt.getText();
        String Trainer_rating = ratingtxt.getText();
        String Trainer_salary = salarytxt.getText();
        String Trainer_join_date = jointxt.getText();
   

        try {
            Connection con = ConnectMSSQL.getCon();
            Statement st = con.createStatement();
            String query = "insert into Trainer(Trainer_name,Trainer_work_hour, Trainer_rating,Trainer_salary,Trainer_join_date)values(?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);

            pst.setString(1, nametxt.getText());
            pst.setString(2, worktxt.getText());
            pst.setString(3, ratingtxt.getText());
            pst.setString(4, salarytxt.getText());
            pst.setString(5, jointxt.getText());
           

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted successfully!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "UnSucessFully Updated");
            System.out.println("notconnect");
        }
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trainer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel joindate;
    private javax.swing.JTextField jointxt;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel rating;
    private javax.swing.JTextField ratingtxt;
    private javax.swing.JButton reset;
    private javax.swing.JLabel salary;
    private javax.swing.JTextField salarytxt;
    private javax.swing.JButton save;
    private javax.swing.JLabel workhour;
    private javax.swing.JTextField worktxt;
    // End of variables declaration//GEN-END:variables
}
